#+LATEX_CLASS: memoir-article
#+LATEX_HEADER: \usepackage{calculating-the-uposatha-moondays}
#+LATEX_HEADER: \renewcommand{\docVersion}{v0.1}
#+LATEX_HEADER: \renewcommand{\docUrl}{\href{https://github.com/profound-labs/calculating-the-uposatha-moondays/}{link}}
#+LATEX_HEADER: \hypersetup{ pdfauthor={Gambhiro Bhikkhu}, }
#+OPTIONS: toc:nil tasks:nil
#+BIBLIOGRAPHY: bibentries plain option:-d
#+SOURCES_URL: https://github.com/profound-labs/calculating-the-uposatha-moondays/
#+AUTHOR: Gambhiro Bhikkhu
#+EMAIL: gambhiro.bhikkhu.85@gmail.com
#+TITLE: Calculating the Uposatha Moondays

#+BEGIN_tldr
- The aim here is to describe the practical steps to calculate the
  uposatha Full- and New Moon days, and indicate the astronomical
  cycles that underlie the method.
- Alternate 30 and 29 day lunar months, 12 months make one year. Add
  an extra month 7 times in every 19 years, add an extra day 11 times
  in every 57 years.
- Conventions on how to practise this can differ by countries and
  groups, resulting in consistent but different calendars.
- Unforseen adjustments to the predicted uposatha days in the
  published Royal Thai Calendar can be expected.
#+END_tldr

#+begin_center
*Unresolved Questions:*

- When is the adhikavara inserted?
- Only Mahanikaya adds adhikavara?

This document is still work-in-progress and represents only what I've
been able to find description of. See the links in the [[#bibliography][Bibliography]] or
download a zip of this document and sources.

Comments, corrections or further information would be greatly
appreciated. ={{{email}}}=
#+end_center

** TODO github zip link in note
* Thailand, Mahānikāya Method
** Alternate 30 and 29 day months

Counting from the last Full Moon of the previous lunar year (which may
be in January), the first month is 30 days, the second is 29 days:

| 15 days | \GaNewmoon{} New Moon | First uposatha of the Cold Season |
| 15 days | \GaFullmoon{} Full Moon | End of first month, 30 days       |
| 15 days | \GaNewmoon{} New Moon |                                   |
| 14 days | \GaFullmoon{} Full Moon | End of second month, 29 days      |

The \GaWaxingmoon{} Waxing- and \GaWaningmoon{} Waning Moons are on the 8th day.

#+begin_latex
\includegraphics[width=\linewidth]{two-months.pdf}
#+end_latex

Keep alternating 30 and 29 day months. One season is four months, one
year is three seasons: Cold-, Hot- and Rainy Season. In a year with
nothing special, the calendar is finished. See Table \ref{tbl-month-names}
for the Pali names of months and seasons.

In some years an extra month (adhikamāsa) or an extra day
(adhikavāra) has to be added.

** Adding the extra month

In Thai practice, the extra month (adhikamāsa) is a 30 day month
inserted after the 8th month (/Āsāḷha/), at the end of the Hot
Season. The convention is to call this the 'second 8th' or 'second
/Āsāḷha/', marked as 8/8.

Vassa starts after the 2nd Āsāḷha, on the day after the Full Moon
uposatha of 8/8.

#+comment: Mahavagga, earlier and later time for the Vassa

| order | name       | days |
|-------+------------+------|
| ...   |            |      |
| 8     | Āsāḷha     |   29 |
| 8/8   | 2nd Āsāḷha |   30 |
| 9     | Savaṇa     |   30 |

The extra month is added 7 times in every 19 year, in a repeating pattern of
3-3-2 - 3-3-3-2 years. See Table \ref{tbl-19yr-adhikamasa}.

#+caption: 19-year cycles of the adhikamāsa\cite{hasapannyo-zodiac}
#+label: tbl-19yr-adhikamasa
|   |  1 | 1997 | 2016 |
|   |  2 |      |      |
| 3 |  3 | 1999 | 2018 |
|   |  4 |      |      |
|   |  5 |      |      |
| 3 |  6 | 2002 | 2021 |
|   |  7 |      |      |
| 2 |  8 | 2004 | 2023 |
|   |  9 |      |      |
|   | 10 |      |      |
| 3 | 11 | 2007 | 2026 |
|   | 12 |      |      |
|   | 13 |      |      |
| 3 | 14 | 2010 | 2029 |
|   | 15 |      |      |
|   | 16 |      |      |
| 3 | 17 | 2013 | 2032 |
|   | 18 |      |      |
| 2 | 19 | 2015 | 2034 |

** Adding the extra day

The extra day (adhikavāra) is added 11 times in every 57 year.

#+begin_quote
It appears to be added every few years in the 3rd uposatha of the Hot Season
-- making it a fifteen-day uposatha instead of the expected
fourteen-day. King Mongkut apparently devised a method to abandon this
practice, but the issue remains a mistery...\cite{hasapannyo-zodiac}
#+end_quote

** Major Moondays

Buddhist communities observe key annual events on the Full Moon
days of four lunar months, see Table \ref{tbl-major-moons}.

#+label: tbl-major-moons
#+caption: Major Moondays
|               | Lunar Month |                                |
| Māgha Pūjā    | 3rd         |                                |
| Visākha Pūjā  | 6th         |                                |
| Āsāḷha Pūjā   | 8th         | Entering Vassa on the next day |
| Assayuja Pūjā | 11th        | Pavāraṇā Day, the end of Vassa |

The Full Moon day is on the last day of a given month. The next month
starts on the following day (first day of the waning phase), thus the
first uposatha will be on a New Moon.

* Adding the extra month, Pali method

/The following is adapted from Ajahn Khemanando for recent
years./\cite{khemanando-adhikamasa}

Table \ref{tbl-cycle-adhikamasa} shows the 19-year cycle between
1997-2034.

#+caption: Adhikamāsa accoding to the Pali method
#+label: tbl-cycle-adhikamasa
|   |    |      |      | Month | Season | New | Full |
|---+----+------+------+-------+--------+-----+------|
|   |  1 | 1997 | 2016 |       |        |     |      |
|   |  2 |      |      |       |        |     |      |
| 3 |  3 | 1999 | 2018 |     5 | Hot    |   4 |  8/8 |
|   |  4 |      |      |       |        |     |      |
|   |  5 |      |      |     2 | Cold   |  12 |    5 |
| 3 |  6 | 2002 | 2021 |       | Cold   |  12 |    5 |
|   |  7 |      |      |       |        |     |      |
| 2 |  8 | 2004 | 2023 |    10 | Rainy  |   8 |   12 |
|   |  9 |      |      |       |        |     |      |
|   | 10 |      |      |       |        |     |      |
| 3 | 11 | 2007 | 2026 |     7 | Hot    |   4 |  8/8 |
|   | 12 |      |      |       |        |     |      |
|   | 13 |      |      |     3 | Cold   |  12 |    5 |
| 3 | 14 | 2010 | 2029 |       | Cold   |  12 |    5 |
|   | 15 |      |      |       |        |     |      |
|   | 16 |      |      |    12 | Cold   |  12 |    5 |
| 3 | 17 | 2013 | 2032 |       | Cold   |  12 |    5 |
|   | 18 |      |      |       |        |     |      |
| 2 | 19 | 2015 | 2034 |     8 | Rainy  |   8 |   12 |

- Month: :: the Thai lunar month into which the adhikamāsa is inserted
- Season: :: the season in which the adhikamāsa fall in that
             particular year
- New and Full: :: the first and last uposatha of the 5-month season
                   in which the adhikamāsa falls, numbered in Thai
                   lunar months

If the adhikamāsa falls on the 2nd, 3rd, or 12th Thai lunar month,
there will be /two/ 8th months (8 and 8/8) the following year.

E.g. In 2001, the adhikamāsa comes as the 2nd lunar month in the
Cold Season, so the following year, 2002, has two 8th months (8 and
8/8). There will thus be /ten/ uposathas in the Cold Season, the
first being the New Moon of the 12th Thai lunar month (2001) and the
last being the Full Moon of the 5th Thai lunar month, 2002.

** TODO note -- is this correct?
It should be remembered that the Pali and Thai ways of reckoning
differ: The Full Moon being the /last/ day of the Pali month, so it is
two weeks ahead of the Thai reckoning, in which the full moon appears
in the /middle/ of the month.

The converse of this -- that the New Moon is the last day of the Thai
month -- means that the New Moon Uposatha is actually in the middle of
the /next/ month compared to the Thai reckoning.

This adhikamāsa calculation seems to be optional these days, and the
complications of a 5-month Vassa, etc. can be avoided by following the
standard Thai calendar's practice of inserting the extra month always
as the last month of the Hot Season.

In which case, all you need to know is that there will be two 8th
month in the following years: 2002, 04, 07, 10, 13, 15, 18.

** TODO illustrate the E.g.
* The Thai luni-solar calendar

Luni-solar calendars are constructed so to count years according to
the /solar/ cycle, but to count months according to the /lunar/ cycle.

| tropical year[fn:tropicalyear] of the Earth | 365.24219 days                      |
| synodic month[fn:synodicmonth] of the Moon  | ~29.53 days, can vary up to 7 hours |

The epoch of the Thai calendar is 25 March 638 CE.

The Thai luni-solar calendar is /procedural/, it uses a couple of
constant, key numbers derived from astronomical observations, and
applies a series of mechanical calculations (i.e. the "rules") again
and again to generate the dates of lunar phases and new years.

#+begin_quote
This working is deliberately concise, since it thereby reflects how
the calculation would have been made by a South East Asian calendrist.
Each stage is subjected to an operation learnt by rote, and the
underlying theory disappears from view. The rote operations, however,
will provide a valid answer for any date in any year. It seemed
greatly preferable to set out the procedure thus starkly, rather than
to give a detailed exposition of what is involved.\cite{eade-interpolation}
#+end_quote

Southeast Asian astronomers refined a fraction to obtain the length of
the year:

\begin{equation}
\frac{292207}{800} = 365.25875 \text{days}
\end{equation}\cite{eade-interpolation}

This is 0.01656 days longer than the modern measurement (1 day in ~60
years). Remarkably, the /suriyayatra/ accounts for this and generates
accurate results:

#+begin_quote
For instance, a Pagan inscription of 14 April 1288 AD maintains that
at midnight the sun's position was 0 signs, 19 degrees and 59 minutes:
the computer program returns 0 19 59.\cite{eade-calendrical}
#+end_quote

Nonetheless, the calendar dates published in Thailand in a given year
reflect not only these principles, but also additional adjustments
which cannot be forseen or retraced.

#+begin_quote
The historical record however, frequently defies prediction, forcing
the conclusion that the pressure upon the /horas/ (astronomers /
astrologers) was not to follow the "rules" but merely, within some
more leisurely constraints, to ensure that the calendar did not get
out of control.\cite{eade-calendrical}
#+end_quote

[fn:tropicalyear] tropical year: the time it takes the Earth to
complete an orbit around the Sun

[fn:synodicmonth] synodic month: the time it takes the Moon to reach
the same visual phase

** Year Types

We are concerned with three types of calendar years:

- Cal A :: Normal with 354 days
- Cal B :: Adhikavāra with 355 days
- Cal C :: Adhikamāsa with 384 days

Comparing these to normal and solar leap years:

|            |   A |   B |   C |
| Lunar      | 354 | 355 | 384 |
| Solar      | 365 | 365 | 365 |
| difference | +11 | +10 | -19 |
|------------+-----+-----+-----|
|            |   A |   B |   C |
| Lunar      | 354 | 355 | 384 |
| Solar Leap | 366 | 366 | 366 |
| difference | +12 | +11 | -18 |

** Adhikamat years

The /suriyayatra/ principle to determine adhikamat years is:

#+begin_quote
"If the day of /thaloengsok/ (astronomical New Year)
lies either within 25 to 29 (in Citta-māsa) or 1 to 5 (in
Visākha-māsa), then the year is adhikamat."\cite{prasert-ngan}
#+end_quote

The /thaloengsok/ is the value of T in Figure \ref{fig-suriyayatra}.

** Adhikawan years

#+begin_quote
Two components of the /suriyayatra/ are known as the /kammacubala/ and
the /avoman/, and it is the values of these two elemets at the start
of the year that determine the matter:

- if the kammacubala value is 207 or less, then the year is leap year
- in a leap year, if the avoman is 126 or less, the year will have an
  extra day
- in a normal year, if the avoman is 137 or less, the year will have
  and extra day\cite{eade-interpolation}
#+end_quote

The /kammacubala/ and /avoman/ are the value of K and A in Figure
\ref{fig-suriyayatra}.

In Thailand, years with an extra month are not allowed to also have an
extra day, and the adhikawan will be assigned to the next year.

** Suriyayatra formulas

\begin{figure}[h]
\caption{Finding astronomical values with the /suriyayatra/ calculation\cite{eade-interpolation}}
\legend{Start with Y, the given Common Era year. Significant values are assigned names. K for \emph{kammacubala}, A for \emph{avoman}, T for \emph{thaloengsok} (the New Year).}
\label{fig-suriyayatra}
\begin{eqnarray*}
a & = & ((Y - 638) * 292207) + 373 \\
h & = & \lfloor a/800 + 1 \rfloor \\
K & = & 800 - a \bmod 800 \\
A & = & ((h*11) + 650) \bmod 692 \\
b & = & \lfloor ((h*11) + 650) / 692 \rfloor \\
T & = & (b + h) \bmod 30
\end{eqnarray*}
\end{figure}

#+attr_latex: :caption: \caption{Adhikamat and adhikawan and in the period 1958 to 1978 (CS 1320-1340).\cite{eade-interpolation}}\legend{'m' for adhikamat, 'd' for adhikawan.}
|    |   |    |   | year | type | Asalha | 2nd Asalha |
|----+---+----+---+------+------+--------+------------|
|    |   |  0 |   | 1320 | m    |  19:42 |      22:24 |
|  0 |   |  1 |   | 1321 | d    |  21:05 |            |
|  1 |   |  2 |   | 1322 |      |  20:40 |            |
|  2 |   |  3 | 3 | 1323 | m    |  19:12 |      22:00 |
|  3 |   |  4 |   | 1324 |      |  20:38 |            |
|  4 | 4 |  5 |   | 1325 | d    |  19:34 |            |
|  5 |   |  6 | 3 | 1326 | m    |  19:38 |      22:05 |
|  6 |   |  7 |   | 1327 |      |  21:15 |            |
|  7 |   |  8 | 2 | 1328 | m    |  19:20 |      22:55 |
|  8 |   |  9 |   | 1329 |      |  21:48 |            |
|  9 | 5 | 10 |   | 1330 | d    |  20:26 |            |
| 10 |   | 11 | 3 | 1331 | m    |  19:59 |      22:50 |
| 11 |   | 12 |   | 1332 |      |  21:20 |            |
| 12 |   | 13 |   | 1333 |      |  20:02 |            |
| 13 |   | 14 | 3 | 1334 | m    |  19:03 |      21:33 |
| 14 | 5 | 15 |   | 1335 | d    |  20:40 |            |
| 15 |   | 16 |   | 1336 |      |  20:44 |            |
| 16 |   | 17 | 3 | 1337 | m    |  19:44 |      22:19 |
| 17 |   | 18 |   | 1338 |      |  21:11 |            |
| 18 |   | 19 | 2 | 1339 | m    |  19:45 |      22:35 |
| 19 | 5 |    |   | 1340 | d    |  21:05 |            |
|    |   |    |   |      |      |        |            |
|    |   |    |   |      |      |        |            |
|    |   |    |   |      |      |        |            |

*** TODO can Prasert's book be found in English?
** Names of the months
   
The name of a given month is determined by the astrological sign which
the Full Moon enters at midnight. See Table \ref{tbl-month-names}.

#+label: tbl-month-names
#+attr_latex: :caption \caption{Lunar and Solar Months and Zodiacs\cite{hasapannyo-zodiac}}\legend{\mA{} marks 29 day months having a 14 day New Moon (\emph{amāvasī cātuddasī}).}
| Season       | Lunar Month        | Solar Month | Solar Zodiac         |
|              |                    |             | (Western / Sanskrit) |
|--------------+--------------------+-------------+----------------------|
| Hemanta-utu  | Magasira-māsa      | December    | Sagittarius / Dhanus |
| Cold Season  | Phussa-māsa\mA     | January     | Capricorn / Makara   |
|              | Māgha-māsa         | February    | Aquarius / Kumbha    |
|              | Phagguṇa-māsa\mA   | March       | Pisces / Mīna        |
|--------------+--------------------+-------------+----------------------|
| Gimha-utu    | Citta-māsa         | April       | Aries / Meṣa         |
| Hot Season   | Visākha-māsa\mA    | May         | Taurus / Vṛṣabha     |
|              | Jeṭṭha-māsa        | June        | Gemini / Mithuna     |
|              | Āsāḷha-māsa\mA     | July        | Cancer / Karkaṭa     |
|--------------+--------------------+-------------+----------------------|
| Vassāna-utu  | Savaṇa-māsa        | August      | Leo / Siṃha          |
| Rainy Season | Bhaddapāda-māsa\mA | September   | Virgo / Kanyā        |
|              | Assayuja-māsa      | October     | Libra / Tulā         |
|              | Kattika-māsa\mA    | November    | Scorpio / Vṛścika    |

*** TODO note on zodiacs, full moon at midnight, etc
* Sri-Lanka :noexport:

Note on differences in times (Vesak, etc.)

* Zodiac :noexport:

Note on zodiacs and lunar months.

** TODO reproduce Aj H's zodiac drawing in Tikz (or Inkscape)
** TODO ? ask for the other side of the drawing
* Motion of the Sun-Earth-Moon system :noexport:
* Bibliography
  :PROPERTIES:
  :CUSTOM_ID: bibliography
  :END:
  

#+begin_latex
\bibliographystyle{plain}
\bibliography{bibentries}
#+end_latex

* Colophon
  
Written in Org-mode. Sources are at [[{{{sources_url}}}][Github]].

Comments, corrections or further information would be greatly
appreciated.

=Gambhiro Bhikkhu <gambhiro.bhikkhu.85@gmail.com>=

Last updated: {{{modification-time}}}


