#+LATEX_CLASS: memoir-article
#+LATEX_HEADER: \usepackage{local}
#+LATEX_HEADER: \renewcommand{\docVersion}{v1.0}
#+LATEX_HEADER: \renewcommand{\docUrl}{\href{https://github.com/profound-labs/calculating-the-uposatha-moondays/}{link}}
#+LATEX_HEADER: \hypersetup{ pdfauthor={Gambhīro Bhikkhu, Hāsapañño Bhikkhu}, }
#+OPTIONS: toc:nil tasks:nil ':t H:4
#+BIBLIOGRAPHY: bibentries plain option:-d
#+SOURCES_URL: https://github.com/profound-labs/calculating-the-uposatha-moondays/
#+AUTHOR: Hāsapañño Bhikkhu, Gambhīro Bhikkhu
#+EMAIL: gambhiro.bhikkhu.85@gmail.com
#+TITLE: Calculating the Uposatha Moondays

#+BEGIN_tldr
- The method is based on a set of formulas called /suriyayatra/ (\thai{สุริยยาตร์}),
  originating from India and including additional rules observed in Southeast
  Asia.
- These formulas are now implemented in [[https://github.com/splendidmoons/suriya-go][suriya-go]] for generating the /uposatha/
  moondays for any arbitrary year.
- The lunar year starts with Magasira month in November. The Seasons end on the
  Full Moon day. The lunar months end on the New Moon day, the Full Moon is in
  the middle. Visākha 15, Āsāḷha 15, etc. is always Full Moon.
- To keep the lunar year in sync with the solar, add an extra month 7 times in
  19 years (the adhikamāsa, \thai{อธิกมาส}), and add an extra day 11 times in 57
  years (the adhikavāra, \thai{อธิกวาร}).
- Conditions on the values produced by formulas determine if a year should be
  assigned an adhikamāsa or adhikavāra.
- The 3-3-2 - 3-3-3-2 shorthand to determine adhikamāsa years is not sufficient.
- Conventions on how to practise this can be differ by countries and monastic groups.
- Common and adhikamāsa years have been regular in past calendars and thus
  reliable to predict. Some adhikavāra years have been irregular, approx. 1
  in 20. However, everything since 1997 have been according to the regular
  pattern.
#+END_tldr

\thispagestyle{empty}

#+begin_latex
\savenotes

\marginpar{\vspace*{-65pt}\footnotesize
``One must acquire the habit of saying `different' rather than `wrong.'\thinspace ''

{\raggedleft
JC Eade, \textit{Calendrical Systems}, p. 4.
\par}}

\spewnotes

\marginpar{\vspace*{\baselineskip}%
\textbf{Just here for the formulas?}

Dive in at sec. \ref{suriyayatra-formulas},
or see how we can ask the machine to do it in Golang at sec. \ref{suriya-go-example}.
}
#+end_latex

#+begin_latex
{\centering\large\bfseries
Reading time:
\par}
#+end_latex

The first section (3 pages) is already informative if you just wish to have a
better understanding of the /uposathas/. The sections get progressively more
involved, drop it when you don't need more.

- 3 pages :: To understand how to construct the sequence of a given year's uposathas, see
  page \pageref{uposatha-tutorial}-\pageref{uposatha-tutorial-end}
  in sec. \ref{uposatha-tutorial}.
- +4 pages :: The formulas and conditions which determine the adhikamāsa and
  adhikavāra are described on page \pageref{suriyayatra-formulas}-\pageref{adhikavara-years-end} in
  sec. \ref{suriyayatra-formulas}.
- +2 pages :: The formulas continue with calculating the angular position
  of the Sun and Moon on a given day at sec. \ref{calculating-the-sun-and-moon}, page
  \pageref{calculating-the-sun-and-moon}-\pageref{calculating-the-sun-and-moon-end}.
- +2 pages :: A given day at the time of midnight is visualized with the zodiac
  wheel diagrams (a.k.a /duang chata/). Making sense of these is in sec. \ref{duangchata},
  page \pageref{duangchata}-\pageref{duangchata-end}.

\clearpage

*** TODO later

Footer on front page:

#+begin_latex
{\centering\large\bfseries
Related:
\par}
#+end_latex

- forestsangha.org wallcalendar and year planner
- suriya-go
- splendid moons
- uposatha .ical link for Google Calendar

Download [[https://github.com/profound-labs/calculating-the-uposatha-moondays/raw/master/calculating-the-uposatha-moondays.pdf][this PDF]] or a [[https://github.com/profound-labs/calculating-the-uposatha-moondays/archive/master.zip][ZIP archive]]. The ZIP contains the PDFs referenced in this document.


small inconsistencies in the uposatha sequence diagrams, text not aligned with
the center of the moons

*** notes                                                          :noexport:

Much appreciation for the answers from the Venerable Ajahns who endured my
questions, in particular Ajahn Hāsapañño and Ajahn Amaro, and the many others
who have helped to correct and improve it. Comprehension and consistency was
only possible with their experience and understanding.

Please send comments, corrections and further information to:

=Gambhiro Bhikkhu <gambhiro.bhikkhu.85@gmail.com>=

* Mahānikāya Uposatha Calendar Tutorial
\label{uposatha-tutorial}

This section is a step-by-step guide on how to calculate the uposathas for the
period of a *solar* year.

The boundaries of lunar months and season overlap. The months end on the day of
the New Moon, the seasons end on the day of the Full Moon. More on this at sec.
\ref{years-seasons}.

** Collecting information about the year

We need to know the following:

- the last uposatha of the previous Rainy Season, Kattika Full Moon
- whether there is an extra lunar month (adhikamāsa),
- or an extra day (adhikavāra),
- or neither, and so this is a common year.

Find the Full Moon in last year November, this is Kattika Full Moon, the last
uposatha of the previous Rainy Season.

In Thai practice a lunar year can't have both an adhikamāsa and an adhikavāra.

Check Table \ref{tbl-cycle-adhikamasa-adhikavara-short} whether the given year
will have an adhikamāsa or adhikavāra. For more data, see Table
\ref{tbl-cycle-adhikamasa-adhikavara}.

#+latex: \begin{margintable}[-100mm]
| Year | \Delta M | \Delta V |
|------+----------+----------|
| 2000 |          |        6 |
| 2001 |          |          |
| 2002 |        3 |          |
| 2003 |          |          |
| 2004 |        2 |          |
| 2005 |          |        5 |
| 2006 |          |          |
| 2007 |        3 |          |
| 2008 |          |          |
| 2009 |          |        4 |
| 2010 |        3 |          |
| 2011 |          |          |
| 2012 |        2 |          |
| 2013 |          |          |
| 2014 |          |          |
| 2015 |        3 |          |
| 2016 |          |        7 |
| 2017 |          |          |
| 2018 |        3 |          |
| 2019 |          |          |
| 2020 |          |        4 |
| 2021 |        3 |          |
| 2022 |          |          |
| 2023 |        2 |          |
| 2024 |          |          |
| 2025 |          |        5 |
| 2026 |        3 |          |
| 2027 |          |          |
| 2028 |          |          |
| 2029 |        3 |          |
| 2030 |          |        5 |
#+latex: \caption{\label{tbl-cycle-adhikamasa-adhikavara-short} 2000-2030.}\legend{\Delta M, \Delta V: years since the last adhikamāsa (M) or adhikavāra (V).}
#+latex: \end{margintable}

Keep in mind that the data on future adhikavāra years is provisional. Even when
a year would be due for an adhikavāra, the calendar authorities may choose to
add it in a different year.

Now we know that the year is either:

- a common year,
- an adhikamāsa year, or
- an adhikavāra year.

Gregorian leap years don't affect the lunar calendar, but it may be useful to
check when planning ahead. Table \ref{tbl-cycle-leap-years} shows a few leap
years.

#+attr_latex: :placement [h] :caption \caption{\label{tbl-cycle-leap-years} Gregorian leap years}
| 2004 | 2016 | 2028 | 2040 |
| 2008 | 2020 | 2032 | 2044 |
| 2012 | 2024 | 2036 | 2048 |

\clearpage

** Common year
\label{common-year}
*** Alternate 30 and 29 day months

#+begin_latex
\begin{fullwidth}
\includegraphics[width=\linewidth]{two-months.pdf}
\end{fullwidth}

\begin{marginfigure}[20mm]
\caption{\label{fig-common-year} Common Year.}
\includegraphics[width=\linewidth]{common-year.png}
\end{marginfigure}
#+end_latex

Kattika is the 12th lunar month, 30 days long. Complete the month by adding a
15-day New Moon after the Full Moon.

The 1st month is Magasira, 29 days long. Add a 15-day Full Moon and a 14-day New
Moon.

| 15 days | \mF{} Full Moon | Kattika  | Last uposatha of the Rainy Season |
| 15 days | \mN{} New Moon  | Kattika  | End of the 12th month, 30 days    |
| 15 days | \mF{} Full Moon | Magasira |                                   |
| 14 days | \mN{} New Moon  | Magasira | End of the 1st month, 29 days     |

The Full Moon is always on the 15th day. Every second New Moon is on the 14th day.

The \GaWaxingmoon{} Waxing- and \GaWaningmoon{} Waning Moons are on the 8th day.

Keep alternating 30 and 29 day months. One season is four months, one year is
three seasons: Cold-, Hot- and Rainy Season. See Figure \ref{fig-common-year} or
Table \ref{tbl-month-names} for the Pāli names of months and seasons.

*** Marking the Vassa and Major Moondays
\label{marking-the-moondays-common-year}

Mark the months and seasons according to Figure \ref{fig-common-year}.

The key annual events are on the Full Moon of the given lunar months.

#+attr_latex: :placement [h] :caption \caption{\label{tbl-major-events} Major Events in a Common Year}
| Event              | Time                 |
|--------------------+----------------------|
| Māgha Pūjā         | 3rd Full Moon        |
| Visākha Pūjā       | 6th Full Moon        |
| Āsāḷha Pūjā        | 8th Full Moon        |
| First Day of Vassa | the day after Āsāḷha |
| Pavāraṇā Day       | 11th Full Moon       |
| Last Day of Vassa  | Pavāraṇā Day         |

Mark the Vassa (Rainy Season Retreat):

- The first day of the Vassa is the day after Āsāḷha Pūjā
- The last day of the Vassa is Pavāraṇā Day

\enlargethispage{2\baselineskip}

The Vassa Retreat therefore is 6 uposathas long (5 + Pavāraṇā), and the Vassāna
season is 8 uposathas.

In a common year, the calendar is finished. 

\clearpage

** Adhikamāsa year
*** Marking the Vassa and Major Moondays
\label{marking-the-moondays-adhikamasa-year}

#+begin_latex
\begin{marginfigure}[-25mm]
\caption{\label{fig-adhikamasa-year} Adhikamāsa Year.}
\includegraphics[width=\linewidth]{adhikamasa-year.png}
\end{marginfigure}

\begin{marginfigure}
\caption{\label{fig-adhikavara-year} Adhikavāra Year.}
\includegraphics[width=\linewidth]{adhikavara-year.png}
\end{marginfigure}
#+end_latex

Adding the extra month has three consequences:

- the Major Moondays shift to the next Full Moon
- Gimhāna (Hot Season) has 10 uposathas instead of 8
- the Vassa starts 30 days later

The extra month is a 30 day month. In Thai practice, it is added after the 8th
month (Āsāḷha). The convention is to call this the 'second 8th' or 'second
Āsāḷha', marked as 8/8. The Hot Season will end on the Full Moon day of the 2nd
Āsāḷha.

Āsāḷha Pūjā will be held in the 8/8 2nd Āsāḷha month, the first day of the
Vassa being on the following day. The Vassa remains the same length, 8 uposathas.

Āsāḷha Pūjā and Pavāraṇā Day therefore shifted 30 days later in the year.

Māgha Pūjā and Visākha Pūjā are moved to the next month, and are marked in the
4th and 7th month instead of the 3rd and 6th. The origin of this practice is not
clear, but it has the advantage that there will not be a large gap between
Visākha and Āsāḷha Pūjā (now in the 2nd Āsāḷha).

# This is as though the Major Moons had a parallel, separate system of numbering,
# in which the adhikamāsa was assumed to be added at the beginning of the year,
# but this doesn't influence the actual numbering or length of the months.

Figure \ref{fig-adhikamasa-year} shows how the sequence of the uposathas and the
major moondays fall in an adhikamāsa year.

** Adhikavāra year

The extra day is inserted at the 7th uposatha of the Hot Season (the New Moon
uposatha before Āsāḷha Full Moon), making it a 15-day uposatha instead of the
expected 14-day, and making Jeṭṭha a 30-day month that
year.\autocite{hasapannyo-zodiac}

In adhikavāra years the Vassa starts one day later.

| order | name    | days |
|-------+---------+------|
|     6 | Visākha |   30 |
|     7 | Jeṭṭha  | *30* |
|     8 | Āsāḷha  |   30 |
|     9 | Savaṇa  |   29 |

#+begin_latex
\includegraphics[width=\linewidth]{adding-the-extra-day.pdf}
#+end_latex

\label{uposatha-tutorial-end}

# Clear floats
\clearpage

* The Mahānikāya Uposatha Calendar Method
** Adding the extra month

The extra month (adhikamāsa) is added 7 times in a 19 year period. This is
determined by the formulas at sec. \ref{suriyayatra-formulas}, which generate a pattern
such that an adhikamāsa year is due in every 2 or 3 years.

It is not sufficient to rely on a shorthand pattern to determine the variation
of 2 or 3 years -- the pattern of 3-3-2 - 3-3-3-2 has been mentioned by Ajahn
Khemanando\autocite{khemanando-adhikamasa}, but this doesn't always match the cycles
produced by the formulas.

Table \ref{tbl-cycle-adhikamasa-adhikavara} shows adhikamāsa years for 1975-2030.

#+latex: \marginpar{%
| order | name       | days |
|-------+------------+------|
| 8     | Āsāḷha     |   30 |
| 8/8   | 2nd Āsāḷha |   30 |
| 9     | Savaṇa     |   29 |
#+latex: }

The extra month is a 30 day month. In Thai practice, it is added after the 8th
month (Āsāḷha). The convention is to call this the 'second 8th' or 'second
Āsāḷha', marked as 8/8. The Hot Season will end on the Full Moon day of the 2nd
Āsāḷha.

In adhikamāsa years the Vassa starts 30 days later, on the day after the Full
Moon uposatha of the 2nd Āsāḷha.

** Adding the extra day
\label{adding-extra-day}

The extra day (adhikavāra) is added 11 times in every 57 year.

Whether a year should have an extra day is determined by the conditions at
sec. \ref{adhikavara-years}.

In Thai practice a year with an extra month is not allowed to also
have an extra day. If the year should have an extra day, but it
already has an extra month, the extra day is assigned to one of the
flanking years (next or previous, in the case of planning several
years in advance).

In adhikavāra years the Vassa starts one day later.

The extra day is inserted at the 7th uposatha of the Hot Season (the New Moon
uposatha before Āsāḷha Full Moon), making it a 15-day uposatha instead of the
expected 14-day, and making Jeṭṭha a 30-day month that
year.\autocite{hasapannyo-zodiac}

The announcement of the adhikavāra years by the calendar authorities is not
entirely predictable. In some of cases the calendar committees add the
adhikavāra in a different year than the regular pattern. However, the years
since 1997 have all been regular.

See Table \ref{tbl-adhikavara-irregularities} for examples of irregular years in the past.

Nonetheless it would be observed that:

- the count for 11 times in 57 years is maintained to keep the
  calendar at pace
- the extra day will not be in years that also have an extra month.
 
** Marking the Vassa and Major Moondays

Common year: sec. \ref{marking-the-moondays-common-year}

Adhikamāsa year: sec. \ref{marking-the-moondays-adhikamasa-year}

Adhikavāra year: the logic is the same as in common years.

#+begin_latex
\begin{table}[h]
\begin{fullwidth}
\caption{\label{tbl-cycle-adhikamasa-adhikavara} Adhikamāsa and adhikavāra years}

\legend{\Delta M, \Delta V: years since the last
adhikamāsa (M) or adhikavāra (V). nM, nV: n-th place in the adhikamāsa
19-year cycle (M) or the adhikavāra 57 year cycle. 'x' marks years which would
qualify for adhikavāra, but there is already an adhikamāsa, and so the
adhikavāra is carried on to the following year.}

\begin{multicols}{2}
#+end_latex

| CE year | BE year | nM | \Delta M | nV | \Delta V |
|---------+---------+----+----------+----+----------|
|    1975 |    2518 | 11 |        3 | 49 |          |
|    1976 |    2519 | 12 |          | 50 |          |
|    1977 |    2520 | 13 |        2 | 51 |          |
|    1978 |    2521 | 14 |          | 52 |        5 |
|    1979 |    2522 | 15 |          | 53 |          |
|    1980 |    2523 | 16 |        3 | 54 |          |
|    1981 |    2524 | 17 |          | 55 |          |
|    1982 |    2525 | 18 |          | 56 |          |
|    1983 |    2526 | 19 |        3 | 57 |          |
|    1984 |    2527 |  1 |          |  1 |        6 |
|    1985 |    2528 |  2 |        2 |  2 |          |
|    1986 |    2529 |  3 |          |  3 |          |
|    1987 |    2530 |  4 |          |  4 |          |
|    1988 |    2531 |  5 |        3 |  5 |          |
|    1989 |    2532 |  6 |          |  6 |        5 |
|    1990 |    2533 |  7 |          |  7 |          |
|    1991 |    2534 |  8 |        3 |  8 |          |
|    1992 |    2535 |  9 |          |  9 |          |
|    1993 |    2536 | 10 |        2 | 10 |          |
|    1994 |    2537 | 11 |          | 11 |        5 |
|    1995 |    2538 | 12 |          | 12 |          |
|    1996 |    2539 | 13 |        3 | 13 |          |
|    1997 |    2540 | 14 |          | 14 |          |
|    1998 |    2541 | 15 |          | 15 |          |
|    1999 |    2542 | 16 |        3 | 16 |        x |
|    2000 |    2543 | 17 |          | 17 |        6 |
|    2001 |    2544 | 18 |          | 18 |          |
|    2002 |    2545 | 19 |        3 | 19 |          |

\columnbreak

| CE year | BE year | nM | \Delta M | nV | \Delta V |
|---------+---------+----+----------+----+----------|
|    2003 |    2546 |  1 |          | 20 |          |
|    2004 |    2547 |  2 |        2 | 21 |        x |
|    2005 |    2548 |  3 |          | 22 |        5 |
|    2006 |    2549 |  4 |          | 23 |          |
|    2007 |    2550 |  5 |        3 | 24 |          |
|    2008 |    2551 |  6 |          | 25 |          |
|    2009 |    2552 |  7 |          | 26 |        4 |
|    2010 |    2553 |  8 |        3 | 27 |          |
|    2011 |    2554 |  9 |          | 28 |          |
|    2012 |    2555 | 10 |        2 | 29 |          |
|    2013 |    2556 | 11 |          | 30 |          |
|    2014 |    2557 | 12 |          | 31 |          |
|    2015 |    2558 | 13 |        3 | 32 |        x |
|    2016 |    2559 | 14 |          | 33 |        7 |
|    2017 |    2560 | 15 |          | 34 |          |
|    2018 |    2561 | 16 |        3 | 35 |          |
|    2019 |    2562 | 17 |          | 36 |          |
|    2020 |    2563 | 18 |          | 37 |        4 |
|    2021 |    2564 | 19 |        3 | 38 |          |
|    2022 |    2565 |  1 |          | 39 |          |
|    2023 |    2566 |  2 |        2 | 40 |          |
|    2024 |    2567 |  3 |          | 41 |          |
|    2025 |    2568 |  4 |          | 42 |        5 |
|    2026 |    2569 |  5 |        3 | 43 |          |
|    2027 |    2570 |  6 |          | 44 |          |
|    2028 |    2571 |  7 |          | 45 |          |
|    2029 |    2572 |  8 |        3 | 46 |          |
|    2030 |    2573 |  9 |          | 47 |        5 |

#+latex: \end{multicols}
#+latex: \end{fullwidth}
#+latex: \end{table}

#+latex: \begin{landscape}
#+latex: \begin{table}[p]
#+latex: \caption{\label{tbl-adhikavara-irregularities} Irregular Adhikavāra years. Past calendar sources: myhora.com, thaiorc.com.}
| CE year | BE year |   K |   A |  T | nM | \Delta M | nV | \Delta V | Āsāḷha by Calc. | Āsāḷha in Calendar | test | comments                                |
|---------+---------+-----+-----+----+----+----------+----+----------+-----------------+--------------------+------+-----------------------------------------|
|    1977 |    2520 |  54 | 252 | 27 | 13 |        2 | 51 |          |      1977-07-30 |         1977-07-30 |      |                                         |
|    1978 |    2521 | 647 | 126 |  9 | 14 |          | 52 |        5 |      1978-07-20 |         1978-07-19 | X    | adhikavāra is missing from the calendar |
|    1979 |    2522 | 440 | 681 | 19 | 15 |          | 53 |          |      1979-07-09 |         1979-07-09 |      |                                         |
|       … |         |     |     |    |    |          |    |          |                 |                    |      |                                         |
|    1983 |    2526 | 412 | 144 |  4 | 19 |        3 | 57 |          |      1983-07-24 |         1983-07-24 |      |                                         |
|    1984 |    2527 | 205 |   7 | 15 |  1 |          |  1 |        6 |      1984-07-13 |         1984-07-12 | X    | adhikavāra is missing                   |
|    1985 |    2528 | 798 | 573 | 26 |  2 |        2 |  2 |          |      1985-08-01 |         1985-07-31 | X    | off by -1 day                           |
|    1986 |    2529 | 591 | 436 |  7 |  3 |          |  3 |          |      1986-07-21 |         1986-07-20 | X    | off by -1 day                           |
|    1987 |    2530 | 384 | 299 | 18 |  4 |          |  4 |          |      1987-07-10 |         1987-07-10 |      |                                         |
|       … |         |     |     |    |    |          |    |          |                 |                    |      |                                         |
|    1993 |    2536 | 742 | 191 | 25 | 10 |        2 | 10 |          |      1993-08-02 |         1993-08-02 |      |                                         |
|    1994 |    2537 | 535 |  54 |  6 | 11 |          | 11 |        5 |      1994-07-23 |         1994-07-22 | X    | adhikavāra is missing                   |
|    1995 |    2538 | 328 | 609 | 16 | 12 |          | 12 |          |      1995-07-12 |         1995-07-11 | X    | off by -1 day                           |
|    1996 |    2539 | 121 | 472 | 27 | 13 |        3 | 13 |          |      1996-07-30 |         1996-07-29 | X    | off by -1 day                           |
|    1997 |    2540 | 714 | 346 |  9 | 14 |          | 14 |          |      1997-07-19 |         1997-07-19 |      |                                         |
#+latex: \end{table}
#+latex: \end{landscape}


# Clear floats
\clearpage

* The Thai luni-solar calendar

Luni-solar calendars are constructed so as to count *years* according to the
/solar/ cycle, but to count *months* according to the /lunar/ cycle.

| tropical year[fn:tropicalyear]\space of the Earth | 365.24219 days                      |
| synodic month[fn:synodicmonth]\space of the Moon  | ~29.53 days, can vary up to 7 hours |

#+begin_latex
\begin{marginfigure}[-\baselineskip]
\raggedright\footnotesize
The program prints:

\begin{verbatim}
Horakhun: 1
Date: 0638 March 25
True Sun: 0:2°38'
True Moon: 0:20°30'
Tithi: 1
\end{verbatim}

Which can be represented on a zodiac wheel:

\bigskip

{\centering
\resizebox{0.9\linewidth}{!}{\DuangChata[Sun={0/2/38}, Moon={0/20/30}, simple]}
\par}

\caption{Horakhun 1, first day of the CS Era}
\end{marginfigure}
#+end_latex

The epoch of the Thai lunar calendar is 25 March 638 CE, this is the beginning
of the /Chulasakkarat Era/.\autocite{eade1995calendrical}

The epoch of the /Buddhist Era/ is the date when the Buddha attained
Parinibbāna. According to Thai tradition it is 11 March 545 BCE, but the
difference between CE and BE in Thailand is now fixed at 543
years.\autocite{eade1995calendrical}

Thus the conversion between the eras:

| CE 1963 | Common Era        |          |
| BE 2506 | Buddhist Era      | CE + 543 |
| CS 1325 | Chulasakkarat Era | CE - 638 |

The Thai luni-solar calendar is /procedural/. It uses a few constant,
key numbers derived from astronomical observations, and applies a
series of mechanical calculations (i.e. the "rules") again and again
to generate the dates of lunar phases and new years.

#+begin_quote
This working is deliberately concise, since it thereby reflects how
the calculation would have been made by a South East Asian calendrist.
Each stage is subjected to an operation learnt by rote, and the
underlying theory disappears from view. The rote operations, however,
will provide a valid answer for any date in any year. It seemed
greatly preferable to set out the procedure thus starkly, rather than
to give a detailed exposition of what is involved.\autocite{eade-interpolation}
#+end_quote

Southeast Asian astronomers refined a fraction to obtain the length of the year.
Taking 800 years as one Era and 292207 days in the Era, they expressesed the
length of one year in days as:\autocite{eade-interpolation}

#+begin_latex
\begin{equation}
\frac{292207}{800} = 365.25875\ \text{days}
\end{equation}
#+end_latex

This is 0.01656 days longer than the modern measurement (accumulating
1 day in ~60 years). Remarkably, the /suriyayatra/ accounts for this
and generates accurate results:

#+begin_quote
For instance, a Pagan inscription of 14 April 1288 AD maintains that
at midnight the Sun's position was 0 signs, 19 degrees and 59 minutes:
the computer program returns
#+latex: 0~19~59.\autocite[p. 2]{eade1995calendrical}
#+end_quote

Let's see if we can get the same results. 14 April 1288 was 41 days into the
lunar year, counting from Citta 1. While checking that, we might as well see day
103, i.e. 15 June 1288, which should turn out to be Āsāḷha Pūjā.

#+begin_latex
\begin{marginfigure}
\caption{1288 April 14}
\raggedright

\resizebox{0.9\linewidth}{!}{\DuangChata[Sun={0/19/58}, Moon={5/11/27}, simple]}

\footnotesize
\bigskip

\begin{tabular}{l l}
Sun: & 0:19\degree 58\minute\\
Moon: & 5:11\degree 27\minute\\
Tithi: & 12
\end{tabular}

\bigskip

The Moon is in the 13. nakshatra, Hasta.

\end{marginfigure}

\begin{marginfigure}
\caption{1288 June 15}
\raggedright

\resizebox{\linewidth}{!}{\DuangChata[Sun={2/19/9}, Moon={8/19/1}, simple]}

\footnotesize
\bigskip

\begin{tabular}{l l}
Sun: & 2:19\degree 9\minute\\
Moon: & 8:19\degree 1\minute\\
Tithi: & 15
\end{tabular}

\bigskip

The Moon is in the 20. nakshatra, Pūrva Ashādhā.

\end{marginfigure}
#+end_latex

The code example is at \ref{golang-1288}. It prints:

: Year: 1288
: Adhikamāsa: false
: Adhikavāra: false
: ---
: Year, Day: 1288, 41
: True Sun: 0:19°58'
: True Moon: 5:11°27'
: Tithi: 12
: ---
: Year, Day: 1288, 103
: True Sun: 2:19°9'
: True Moon: 8:19°1'
: Tithi: 15

On day 103, tithi 15 means 15 lunar days since last New Moon, i.e. it is Full
Moon. The Sun and Moon are angularly opposite, which also means Full Moon, and
it appears in the 20. nakshatra, so the month is Āsāḷha.

#+latex: As a reality check, we can look up the historical phases and see if
#+latex: the day is listed under the Full Moons:\footnote{\href{http://astropixels.com/ephemeris/phasescat/phases1201.html}{AstroPixels - Moon Phases: 1201 to 1300}}

#+latex: {\centering
#+latex: \includegraphics[width=0.8\linewidth]{1288-astropixels.png}
#+latex: \par}

Nonetheless, the calendar dates published in Thailand (historical or
recent) in a given year reflect not only these principles, but also
adjustments and omissions which cannot be foreseen or retraced.

#+begin_quote
The historical record however, frequently defies prediction, forcing
the conclusion that the pressure upon the /horas/ (astronomers /
astrologers) was not to follow the "rules" but merely, within some
more leisurely constraints, to ensure that the calendar did not get
out of control.\autocite{eade1995calendrical}
#+end_quote

Eade discusses a calendar error in CS 855 (CE 1493) when the formulas have
determined a /twelfth/ adhikavāra year in a 57 year period, which was not
noticed by several astronomers at the time, who were using the "11 times in 57
years" rule of thumb for adhikavāra years. This resulted in wrong dates being
used on any inscriptions (carved into stone) until the error was corrected in
the civil calendar.\autocite{eade2007irregular}

# If this \clearpage is after the fn texts, it is included in them
# \clearpage

[fn:tropicalyear] tropical year: the time it takes the Earth to
complete an orbit around the Sun

[fn:synodicmonth] synodic month: the time it takes the Moon to reach
the same visual phase

** Date of New Year in Thailand

The officially used new year date in Thailand is January 1st, after a government
ruling in 1940:

"...it is now appropriate for Thailand to observe New Year's Day on the first
day of January."\autocite{wp-thai-new-year-day}

The Songkran festival, commonly called the Thai New Year, is held on April
13-14-15, at the time of the spring equinox.

** Time periods in the Calendar
\label{years-seasons}

*** Years

The reckoning of the lunar year has an everyday convention which is aligned with
the solar year. Here, the first month of the lunar year is Magasira in November.

By this reckoning Āsāḷha is the 8th month, and hence the 2nd Āsāḷha is marked
8/8, \thai{เดือน ๘/๘}.

A different reckoning is assumed in the formulas which is based on the zodiac
wheel. Here, the first month is Citta in April. This is at the spring equinox,
which is at 0\degrees{} on the wheel, corresponding to Aries.

*** Months

In Thai practice, a lunar month is a wave: it has a waxing phase, its crest is
in the middle at Full Moon, and has a waning phase ending with the New Moon on
the last day.

The lunar months (duean \thai{เดือน}) are alternatingly 29 or 30 days long. The
waxing phase (khang khuen \thai{ข้างขึ้น}) to the Full Moon is always 15 days,
every second waning phase (khang raem \thai{ข้างแรม}) is 14 days.\autocite{wp-thai-lunar-calendar}

This convention gives a consistent way to refer to the day of the Full Moon,
which are always on the 15th day of the month: Visākha 15, Āsāḷha 15, etc.

The waxing and waning moons are marked on the 8th day from the Full- or New Moon
day.

\clearpage

*** Seasons

#+latex: \marginpar{%
| Cold Season  | Hemanta     |
| ends on:     | Phagguṇa 15 |
|--------------+-------------|
| Hot Season   | Gimhāna     |
| ends on:     | Āsāḷha 15   |
|--------------+-------------|
| Rainy Season | Vassāna     |
| ends on:     | Kattika 15  |
#+latex: }

The first season of the lunar year is the Cold Season, which begins after
Kattika Full Moon.

Marking the seasons is a monastic tradition. Periods in the monastic calendar
are observed between certain Full Moon days of the year, and so the seasons end
on Full Moon days.

The lunar months end on the New Moon day, the month and season boundaries
therefore overlap.

The months and seasons are two separate way of referencing lunar phases, they
are never used together in the same expression.

They are used in different contexts too, so the overlap doesn't seem to bother
anyone. The civil calendar marks periods by /months/ in the year, but the
monastic calendar is concerned instead with the number of /uposathas/ in the
season.

#+latex: The monastic tradition references Full- and New Moons as the ``Nth uposatha of the X~Season.''

*** Days

A 'day' marks the time at midnight on that day, unless the time is specified.
Positions of the Sun, the Moon and other calculated properties of the day are
understood to reach that value at midnight.

** Names of the months

The zodiac wheel is divided in 27 segments called /nakshatra/, associated with
and area of the sky around certain stars.

The name of a given month is determined by the nakshatra which the Full Moon
enters at midnight. See Table \ref{tbl-month-names}.

\savenotes

#+attr_latex: :placement [h] :caption \caption{\label{tbl-month-names} Lunar and Solar Months and Zodiacs\autocite{hasapannyo-zodiac}}
| Season       |    |      | Lunar Month | Solar Month | Solar Zodiac         |
|              |    | days |             |             | (Western / Sanskrit) |
|--------------+----+------+-------------+-------------+----------------------|
| Hemanta      |  1 |   29 | Magasira    | December    | Sagittarius / Dhanus |
| Cold Season  |  2 |   30 | Phussa      | January     | Capricorn / Makara   |
|              |  3 |   29 | Māgha       | February    | Aquarius / Kumbha    |
|              |  4 |   30 | Phagguṇa    | March       | Pisces / Mīna        |
|--------------+----+------+-------------+-------------+----------------------|
| Gimhāna      |  5 |   29 | Citta       | April       | Aries / Meṣa         |
| Hot Season   |  6 |   30 | Visākha     | May         | Taurus / Vṛṣabha     |
|              |  7 |   29 | Jeṭṭha      | June        | Gemini / Mithuna     |
|              |  8 |   30 | Āsāḷha      | July        | Cancer / Karkaṭa     |
|--------------+----+------+-------------+-------------+----------------------|
| Vassāna      |  9 |   29 | Savaṇa      | August      | Leo / Siṃha          |
| Rainy Season | 10 |   30 | Bhaddapāda  | September   | Virgo / Kanyā        |
|              | 11 |   29 | Assayuja    | October     | Libra / Tulā         |
|              | 12 |   30 | Kattika     | November    | Scorpio / Vṛścika    |

\spewnotes

# Big tables that need a separate page

\savenotes

#+attr_latex: :placement [h] :caption \caption{\label{tbl-calendars-1958} Adhikamāsa and adhikavāra in the period 1958 to 1978 (CS 1320-1340).\autocite{eade-interpolation}}\legend{m for adhikamāsa, d for adhikavāra years, \Delta m and \Delta d for years since last adhikamāsa and adhikavāra.}
|    | \Delta d |    | \Delta m | year | type | Asalha | 2nd Asalha |
|----+----------+----+----------+------+------+--------+------------|
|    |          |  0 |          | 1320 | m    |  19:42 |      22:24 |
|  0 |          |  1 |          | 1321 | d    |  21:05 |            |
|  1 |          |  2 |          | 1322 |      |  20:40 |            |
|  2 |          |  3 |        3 | 1323 | m    |  19:12 |      22:00 |
|  3 |          |  4 |          | 1324 |      |  20:38 |            |
|  4 |        4 |  5 |          | 1325 | d    |  19:34 |            |
|  5 |          |  6 |        3 | 1326 | m    |  19:38 |      22:05 |
|  6 |          |  7 |          | 1327 |      |  21:15 |            |
|  7 |          |  8 |        2 | 1328 | m    |  19:20 |      22:55 |
|  8 |          |  9 |          | 1329 |      |  21:48 |            |
|  9 |        5 | 10 |          | 1330 | d    |  20:26 |            |
| 10 |          | 11 |        3 | 1331 | m    |  19:59 |      22:50 |
| 11 |          | 12 |          | 1332 |      |  21:20 |            |
| 12 |          | 13 |          | 1333 |      |  20:02 |            |
| 13 |          | 14 |        3 | 1334 | m    |  19:03 |      21:33 |
| 14 |        5 | 15 |          | 1335 | d    |  20:40 |            |
| 15 |          | 16 |          | 1336 |      |  20:44 |            |
| 16 |          | 17 |        3 | 1337 | m    |  19:44 |      22:19 |
| 17 |          | 18 |          | 1338 |      |  21:11 |            |
| 18 |          | 19 |        2 | 1339 | m    |  19:45 |      22:35 |
| 19 |        5 |    |          | 1340 | d    |  21:05 |            |

\spewnotes

# Clear floats
\clearpage

** Year Types and lengths                                          :noexport:

#+latex: \begin{multicols}{2}

We are concerned with three types of calendar years:

- Cal A :: Normal with 354 days
- Cal B :: Adhikavāra with 355 days
- Cal C :: Adhikamāsa with 384 days

#+latex: \columnbreak

Comparing these to normal and solar leap years:

|            |   A |   B |   C |
| Lunar      | 354 | 355 | 384 |
| Solar      | 365 | 365 | 365 |
| difference | +11 | +10 | -19 |
|------------+-----+-----+-----|
|            |   A |   B |   C |
| Lunar      | 354 | 355 | 384 |
| Solar Leap | 366 | 366 | 366 |
| difference | +12 | +11 | -18 |

#+latex: \end{multicols}

* Suriyayatra formulas
\label{suriyayatra-formulas}
** Overview

The formulas take two inputs: the year, and the n^th day in the lunar year.
They go through a series of operations step by step to produce certain values
which describe properties of the lunar year and the given day.

In this context, the lunar year starts at the spring equinox: this is 0\degree{}
on the zodiac wheel, Aries, Citta 1, April.

The results are used to determine whether the year is common, adhikamāsa or
adhikavāra. They can also give us the angular position of the Sun and the Moon
on a particular day.

#+begin_latex
\begin{marginfigure}[-10mm]
\raggedright
\caption{\label{fig-wheel-2014-asalha} 2014 July 11, Āsāḷha Full Moon}

\resizebox{\linewidth}{!}{\DuangChata[Sun={2/25/22}, Moon={8/16/6}, simple]}

\footnotesize
\bigskip

\begin{tabular}{l l}
True Sun: & 2:25\degree 22\minute\\
True Moon: & 8:16\degree 6\minute\\
Raek: & 20:12\minute\\
Masaken: & 17022\\
Avoman: & 391\\
Horakhun: & 502683\\
Kammacubala: & 69195\\
Uccabala: & 1102\\
Tithi: & 14
\end{tabular}

\bigskip

At midnight the Moon would be seen in the 20. Nakshatra, Pūrva Ashādhā, around the stars δ and ε Sagittarii.

\end{marginfigure}
#+end_latex

For example in a common year, when we calculate the Moon's position for
$\mathbf{day} = 103$, it should tell us that it is Full Moon, and it is found in
the region of the sky associated with Āsāḷha month.

Significant values are assigned names.\autocite{eade1989ephemeris} The following
three will determine the adhikamāsa and adhikavāra:

\savenotes

- Kammacubala \thai{กัมมัชพล} :: used as a remainder value for 800ths of a day,\\
  1 day = 800 kammacubala
- Avoman \thai{อวมาน} :: used for the Moon's mean motion,\\ 1 day = 11 avoman
- Tithi\footnote{a.k.a. Thaloengsok or New Year's Day} \thai{ดีถี} :: age of the Moon in /lunar/ days, from 0-29, \\
  692 solar days = 692 + 11 lunar days

As we follow the steps, we will also obtain:

- Horakhun\footnote{a.k.a. Ahargana} \thai{อหรคุณ} :: day index, or elapsed days of the era
- Uccabala \thai{อุจจพล} :: age of the Moon's apogee
- Masaken \thai{มาสเกณฑ์} :: elapsed months of the era

- MeanSun, TrueSun, MeanMoon, TrueMoon :: Mean- and True longitude of the Sun and the Moon
- Raek :: The position of the Moon in terms of the 27 lunar mansions, which will determine the month

#+begin_latex
\marginpar{\vspace*{-5\baselineskip}\footnotesize
While mean longitude measures a mean position and assumes constant speed,
true longitude meausures the actual longitude and assumes the body has moved
with its actual speed, which varies around its elliptical \mbox{orbit}.\autocite{wp-mean-longitude}
}
#+end_latex

\spewnotes

The zodiac wheel (a.k.a /duang chata/, sec. \ref{duangchata}) is divided into 12
segments called /rasi/ (\thai{ราศี}), $30\degree$ each, and into 27 lunar
mansions called /nakshatra/ (\thai{นักษัตร}), $13\degree 20\minute$ each.

Angular positions are given in a notation that expresses the rasi number plus
the degrees and arcminutes. These values are also called the /rasi/, /angsa/ and
/lipda/.

#+latex: \marginpar{\vspace*{-2\baselineskip}\footnotesize
$2:25\degree 22\minute$ notation represents /rasi/, /angsa/ (degrees), /lipda/ (minutes).

$r:a\degree l\minute = r*30 + a + l/60$,\\
thus $85\degree 22\minute$ is $2:25\degree 22\minute$.
#+latex: }

Only basic operations in a series of simple steps are necessary to produce these
results. It can be carried out entirely on paper, although the aim here is to
get the machine to do it for us eventually.

This is a simplistic clockwork model of the solar system. It is not a framework
to model orbital mechanics, and doesn't account for such things as the varying
speed of the Moon in its elliptical orbit.

Therefore there can be inaccuracies for a given day between its results and
observations made with telescopes (or indeed by plain sight) about what is
actually going on "out there", but nonetheless it keeps the long-term calendar
in sync with the periodic cycles of the celestial bodies.

Consider the ancient /hora/ \thai{โหรา} (astronomer / astrologer) in a rural village who is
practising these steps. He doesn't have the equipment to make precise
astronomical observations. He is not educated in the underlying theory of the
complex interaction of the Sun, Earth and the Moon. He is only trained in
following the steps, and still this allows him to obtain the necessary
information to describe the progression of these events in any year.

** Calculating the properties of the year

First we will see if we should add an extra month or extra day to keep the
lunar year in sync with the solar year.

Then we will calculate the position of the Moon for the day that should be
Āsāḷha Pūjā, see if the Moon is Full, and if we are in fact in Āsāḷha month, and
not at some other Full Moon.

We can also use other sources to check us, looking up historical phases of the
Moon can show us if the Āsāḷha Pūjā date had in fact been a Full Moon.

Let's take the year CE 1963 (CS 1325) as an example and calculate its
properties. We should find that it is an adhikavāra year. If you calculate the
following year CE 1964 (CS 1326) as an excercise, you should find that it is
adhikamāsa.

#+begin_latex

Era Constants. The offsets are required because their value was not 0 at the beginning of the Era.
For readability, where the meaning is not ambiguous, we will use their values directly.

\bigskip

\begin{fullwidth}
\begin{multicols}{2}

\begin{tabular}{l l l}
  $CS_{diff}    $ & $638   $ & CE - CS Era difference \\
	$Days_{Era}   $ & $292207$ & Days in the Era \\
	$Years_{Era}  $ & $800   $ & Years in the Era \\
	$H_{Era}      $ & $373   $ & Horakhun Era offset \\
	$U_{Era}      $ & $2611  $ & Uccabala Era offset \\
	$A_{Era}      $ & $650   $ & Avoman Era offset \\
\end{tabular}

\columnbreak

\begin{tabular}{l l l}
  $U_{base}     $ & $3232  $ & Uccabala base for 360\degrees \\
	$Days_{M}     $ & $30    $ & Days in a month \\
	$Days_{Cycle} $ & $692   $ & Days in a cycle \\
	$Tithi_{Cycle}$ & $703   $ & Tithi in a cycle \\
	$Tithi_{inc}  $ & $11    $ & Tithi daily increase \\
	$Kc_{inc}     $ & $800   $ & Kammacubala daily increase \\
\end{tabular}

\end{multicols}
\end{fullwidth}

\makeatletter
\newcommand\cheatsheetText{%
\begin{tabular}{l l}
  $CS_{diff}    $ & $638   $ \\
	$Days_{Era}   $ & $292207$ \\
	$Years_{Era}  $ & $800   $ \\
	$H_{Era}      $ & $373   $ \\
	$U_{Era}      $ & $2611  $ \\
	$A_{Era}      $ & $650   $ \\
  $U_{base}     $ & $3232  $ \\
	$Days_{M}     $ & $30    $ \\
	$Days_{Cycle} $ & $692   $ \\
	$Tithi_{Cycle}$ & $703   $ \\
	$Tithi_{inc}  $ & $11    $ \\
	$Kc_{inc}     $ & $800   $ \\
\end{tabular}%
}

\newcommand\cheatsheetPar{\marginpar{\vspace*{1\baselineskip}\footnotesize\cheatsheetText}}

\makeatother

% 3232 is a "base" for 360 degrees.\autocite[p. 48]{eade1995calendrical}

\clearpage

The relationship between cycles of \textbf{solar days} and \textbf{tithi} (lunar days):
"For every 692 solar days that elapse there are also 703 tithi.
Since 703 / 692 can be expressed as 692 + 11 / 692, the ratio is simplified to these terms ...
11 is the daily increase (excess tithi over days)."\autocite[p. 48]{eade1995calendrical}

\begin{equation}
\frac{703}{692} = \frac{692 + 11}{692}
\end{equation}

\marginpar{%
\vspace*{-6\baselineskip}%
\setlength{\parskip}{5pt}%
\footnotesize

Notation recap:

$a \bmod b$ produces the \textit{remainder part} of $a/b$.

$14 \bmod 5 = 4$, because\\ $14/5 = 2*5 + 4$.

$\lfloor a \rfloor$ \textit{floors} (or truncates) a fraction value, meaning we discard
the fraction part and only keep the integer part.

$\lfloor 12.8 \rfloor = 12$.

$|a|$ is the \textit{absolute value} of $a$.

$|-4.21| = 4.21$ and $|4.21| = |4.21|$.
}

Let's begin then:

\cheatsheetPar

\begin{align}
\begin{split}
   \mathbf{CS\_year} &= \mathbf{CE\_year} - 638\\
                     &= 1325
\end{split}\\
\begin{split}
                   a &= (\mathbf{CS\_year} * 292207) + 373\\
                     &= 387174648
\end{split}\\
\begin{split}
\mathbf{Horakhun}    &= \lfloor a / 800 + 1 \rfloor\\
                     &= 483969
\end{split}\\
\begin{split}
\mathbf{Kammacubala} &= 800 - (a \bmod 800)\\
                     &= 552
\end{split}\\
\begin{split}
\mathbf{Uccabala}    &= (\mathbf{Horakhun} + 2611) \bmod 3232\\
                     &= 1780
\end{split}\\
\begin{split}
                   a &= (\mathbf{Horakhun} * 11) + 650\\
                     &= 5324309
\end{split}\\
\begin{split}
\mathbf{Avoman}      &= a \bmod 692\\
                     &= 61
\end{split}\\
\begin{split}
                   b &= \lfloor a / 692 \rfloor\\
                     &= 7694
\end{split}\\
\begin{split}
\mathbf{Masaken}     &= \lfloor (b + \mathbf{Horakhun}) / 30 \rfloor\\
                     &= 16388
\end{split}\\
\begin{split}
\mathbf{Tithi}       &= (b + \mathbf{Horakhun}) \bmod 30\\
                     &= 23
\end{split}
\end{align}

#+end_latex

Now we can determine if the year qualifies for adhikamāsa or adhikavāra.

\clearpage

** Adhikamāsa conditions
\label{adhikamasa-years}

#+latex: \marginpar{Thai: atikamat \thai{อธิกมาส}}

The year could be adhikamāsa:

- \logic{IF} the *Tithi* is between 24 and 29 inclusive,
- \logic{OR} between 0 and 5 inclusive,
- \logic{then} it could be adhikamāsa.
  
However:

- \logic{IF} the next year also satisfies the above,
- \logic{then} this year will not be adhikamāsa, and the next year will be.

Adhikamāsa years are not allowed to be contiguous, and max. 2 years are allowed
between them. If next year also qualifies for adhikamāsa, then it will be
assigned there and not to the current year.

In the above example for year CS 1325, the *Tithi* is 23, which doesn't satisfy
the first condition, and so it can't be adhikamāsa.

*** notes                                                          :noexport:

The /suriyayatra/ principle to determine adhikamāsa years is:

# TODO: update this as according to go code

#+begin_quote
Faraut (p. 65) says that a year will be adhikamāsa if it begins between 26
Caitra and 5 Vaisakha, but in fact the range extends to 6 Vaisakha at one end,
and at the other end 24 Caitra is capable of being A, B, or C, depending on the
condition of the years that flank it.

Eade, Calendrical, p.64 footnote 52
#+end_quote

#+begin_quote
If the day of /tithi/ (astronomical New Year)
lies either within 25 to 29 (in Citta-māsa) or 1 to 5 (in
Visākha-māsa), then the year is adhikamāsa.\autocite{prasert-ngan}

Eade, in Interpolation
#+end_quote

#+begin_quote
Two components of the /suriyayatra/ are known as the /kammacubala/ and
the /avoman/, and it is the values of these two elements at the start
of the year that determine the matter:

- if the kammacubala value is 207 or less, then the year is leap year
- in a leap year, if the avoman is 126 or less, the year will have an
  extra day
- in a normal year, if the avoman is 137 or less, the year will have
  and extra day\autocite{eade-interpolation}
#+end_quote

** Adhikavāra conditions
\label{adhikavara-years}

#+latex: \marginpar{Thai: atikawan \thai{อธิกวาร}}

Determine if it is a leap year:

- \logic{IF} the *Kammacubala* is less than or equal to 207,
- \logic{THEN} it is a leap year.

The year could be adhikavāra:

- \logic{IF} it is a leap year \logic{AND} the *Avoman* is less than or equal to 126,
- \logic{then} it could be adhikavāra.
- \logic{ELSE IF} it is \logic{NOT} a leap year \logic{AND} the *Avoman* is less than 137,
- \logic{then} it could be adhikavāra.

#+latex: \marginpar{\footnotesize
"Carried adhikavāra" meaning that last year qualified both for adhikamāsa and
adhikavāra, so it was not allowed to be assigned the adhikavāra, which was
"carried on" and will now be assigned to this year.

In Thailand, years with an extra month are not allowed to also have an extra
day, and the adhikavāra may be assigned to one of the flanking years. So in
theory it could be assigned to the following or preceding year, but the general
practice is to "carry on" the adhikavāra and assign it to the following year.
#+latex: }

However:

- \logic{IF} the year is adhikamāsa,
- \logic{then} it can't be adhikavāra.
- \logic{ELSE IF} there is a carried adhikavāra from last year,
- \logic{then} this year will be adhikavāra.

In the above example for year CS 1325: The year is not adhikamāsa, so we can
examine it further. The *Kammacubala* is 552 so it is not a leap year. The
*Avoman* is 61, so the year qualifies to be assigned an adhikavāra.

Now we know if the year is adhikamāsa, adhikamāsa or common, and we can plan the
uposathas as shown in the diagram on
p.\pageref{dia-common-adhikamasa-adhikavara}.

Checking the past calendars for year CS 1325 (see Table
\ref{tbl-calendars-1958}), we see that indeed it was adhikavāra, conforming to
the formulas.

Nonetheless, the future remains uncertain and the past inscrutable at times.
When the calendar comittees plan several years ahead, they may assign the
adhikavāra to a different year for reasons that remain obscured, causing at
least two irregular years. This can be observed in past calendars (Table
\ref{tbl-adhikavara-irregularities}), but recently this hasn't been happening,
and the years follow the prediction of the formulas.

\label{adhikavara-years-end}

** Calculating the Position of the Sun and the Moon
\label{calculating-the-sun-and-moon}

Eade describes the formulas at the end of his paper /Rules for interpolation in
the Thai calendar/.\autocite{eade2000rules} This allows us to continue examining
the year CE 1963 (CS 1325).

#+latex: \marginpar{\vspace*{-1.5\baselineskip}\footnotesize
His notation however, is a puzzle in \mbox{itself}, with its implied conversions and
obscure progression from one step to the next.

The folks at [[http://astronomy.stackexchange.com/][Astronomy Stack Exchange]] helped to decipher it:

- [[http://astronomy.stackexchange.com/questions/11753/how-to-interpret-this-old-degree-notation][How to interpret this old degree notation?]]
- [[http://astronomy.stackexchange.com/questions/12052/from-mean-moon-to-true-moon-in-an-old-procedural-calendar][From Mean Moon to True Moon in an old procedural calendar]]
#+latex: }

We know now that the year needed an adhikavāra extra day, so Āsāḷha Pūjā is one
day later, on day 104, which is 1963 July 6. Let's find the position of the Sun
and the Moon on that day, to see if the Moon reached its Full phase, and if it
is in the region of the sky associated with the correct month (i.e. the
nakshatra).

The *Horakhun*, etc. values now relate to the *day*, unless marked otherwise.
First we establish the properties of the day:

#+begin_latex
\cheatsheetPar

\begin{align}
\begin{split}
   \mathbf{elapsedDays} &= \mathbf{Day} - \mathbf{Year\_Tithi}\\
                        &= 81
\end{split}\\
\begin{split}
   \mathbf{Horakhun}    &= \mathbf{Year\_Horakhun} + \mathbf{elapsedDays}\\
                        &= 484050
\end{split}\\
\begin{split}
  \mathbf{Kammacubala}  &= Kc_{inc} - (\mathbf{CS\_Year} * 292207 + 373) \bmod Years_{Era}\\
                        & \quad + \mathbf{elapsedDays} * Kc_{inc}\\
                        &= 65352
\end{split}\\
\begin{split}
  \mathbf{Uccabala}     &= (\mathbf{Horakhun} + 2611) \bmod 3232\\
                        &= 1861
\end{split}\\
\begin{split}
                      a &= (\mathbf{Horakhun} * 11) + 650\\
        \mathbf{Avoman} &= a \bmod 692\\
                        &= 260
\end{split}\\
\begin{split}
                      b &= \lfloor a / 692 \rfloor + 2611 + \mathbf{Horakhun}\\
       \mathbf{Masaken} &= \lfloor b / 30 \rfloor\\
                        &= 16391
\end{split}\\
\begin{split}
         \mathbf{Tithi} &= b \bmod 30\\
                        &= 15
\end{split}
\end{align}

#+end_latex

Find the position of the *Mean* and *True Sun*:

Degree to radian conversion noted as $a_{rad} = a * \frac{\pi}{180}$.

Note that 60 converts values between degrees and arcminutes: 

#+latex: \[ a\degree*60=b\minute \quad \text{and} \quad b\minute/60 = a\degree \]

\clearpage

#+begin_latex
\cheatsheetPar

\begin{align}
\begin{split}
                      a &= \mathbf{elapsedDays} * Years_{Era} + \mathbf{Year\_Kammacubala}\\
       \mathbf{MeanSun} &= (a / Days_{Era}) * 360\degree - 3\minute\\
                        &= 80.45\degree = 2:20\degree 27\minute
\end{split}\\
\begin{split}
                         a &= | \mathbf{MeanSun} - 80\degree | \\
          \mathbf{TrueSun} &= \mathbf{MeanSun} + \frac{\lfloor 134 * \mathit{sin}(a_{rad}) \rfloor}{60}\\
                           &= 80.4666\degree = 2:20\degree 27\minute
\end{split}
\end{align}
#+end_latex

Find the position of the *Mean* and *True Moon*:

\savenotes

#+begin_latex
\marginpar{%
\setlength{\parskip}{5pt}%
\footnotesize

$-3\minute$ and $-40\minute$ are geographical correction for the Sun and the Moon.\autocite[p. 6, fn. 13]{eade2000rules}

$-80\degree$ is the Sun's apogee value for Mean- to True longitude conversion.\autocite[p. 134]{eade1995calendrical}

One \textbf{Tithi} is 12\degree, from\\
$360\degree / 30 = 12\degree$.
}

\spewnotes

\begin{align}
\begin{split}
                  a &= \frac{\mathbf{Avoman} + \lfloor \mathbf{Avoman} / 25 \rfloor}{60}\\
  \mathbf{MeanMoon} &= \mathbf{TrueSun} + a\degree + \mathbf{Tithi} * 12\degree - 40\minute\\
                    &= 264.2999\degree = 8:24\degree 17\minute
\end{split}
\end{align}

The \textbf{meanUccabala} in one step:

\begin{align}
\begin{split}
	\mathbf{meanUccabala} &= \left( \frac{(\mathbf{Year\_Uccabala} + \mathbf{elapsedDays}) * 3}{808} * 30 * 60 + 2 \right) / 60\\
                        &= 207.4343\degree = 6:27\degree 26\minute
\end{split}
\end{align}
#+end_latex

Breaking it down:

- Multiply by 30 to conform with the notation $r:a\degree l\minute = 30*r + a + l/60$.
- Division by 808 probably helps to express the length of the lunar month, since $808 / 30 = 26.9333$.
- Multiply by 60 to convert to arcmin
- Add 2, correction for geographical position
- Divide by 60 to convert back to degree

#+begin_latex
\marginpar{\footnotesize $13\degree 20\minute$ is one nakshatra or lunar mansion, $360\degree / 27$.}

\begin{align}
\begin{split}
                 a &= \mathbf{MeanMoon} - \mathbf{meanUccabala}\\
 \mathbf{TrueMoon} &= \mathbf{MeanMoon} - \frac{296 * \mathit{sin}(a_{rad})}{60}\\
                   &= 260.1636\degree = 8:20\degree 9\minute
\end{split}\\
\begin{split}
     \mathbf{Raek} &= \mathbf{TrueMoon} / 13\degree 20\minute + 1\\
                   &= 20.5123\degree = 20\degree 30\minute
\end{split}
\end{align}

\begin{fullwidth}%
% ============================================== %
\begin{minipage}{0.33\linewidth}
\centering

Day 103, 1963 July 5
\bigskip

\resizebox{!}{0.55\height}{\DuangChata[Sun={2/19/28}, Moon={8/7/41}, simple]}

\bigskip

\begin{tabular}{l l}
Sun: & 2:19\degree 28\minute\\
Moon: & 8:7\degree 41\minute\\
Tithi: & 14
\end{tabular}

\bigskip

19. nakshatra, Mūla.

\end{minipage}%
% ============================================== %
\begin{minipage}{0.33\linewidth}
\centering

Day 104, 1963 July 6
\bigskip

\resizebox{!}{0.55\height}{\DuangChata[Sun={2/20/27}, Moon={8/20/9}, simple]}

\bigskip

\begin{tabular}{l l}
Sun: & 2:20\degree 27\minute\\
Moon: & 8:20\degree 9\minute\\
Tithi: & 15
\end{tabular}

\bigskip

20. nakshatra, Pūrva Ashādhā.

\end{minipage}%
% ============================================== %
\begin{minipage}{0.33\linewidth}
\centering

Day 105, 1963 July 7
\bigskip

\resizebox{!}{0.55\height}{\DuangChata[Sun={2/21/28}, Moon={9/2/51}, simple]}

\bigskip

\begin{tabular}{l l}
Sun: & 2:21\degree 28\minute\\
Moon: & 9:2\degree 51\minute\\
Tithi: & 16
\end{tabular}

\bigskip

21. nakshatra, Uttara Ashādhā.

\end{minipage}%
% ============================================== %
\end{fullwidth}

\bigskip

Let's look up if 1963 July 6 is listed under Full Moons:\footnote{\href{http://astropixels.com/ephemeris/phasescat/phases1901.html}{AstroPixels - Moon Phases: 1901 to 2000}}

\bigskip

{\centering
\includegraphics[width=0.8\linewidth]{1963-astropixels.png}
\par}
#+end_latex

\label{calculating-the-sun-and-moon-end}

\clearpage

*** notes                                                          :noexport:

# TODO note BKK location ประเทศไทย (UTC+07:00) กรุงเทพ ฯ นักษัตร์ ละติจูด 13.75258° ลองติจูด 105.00000°

# ดาว	ราศี	องศา	ลิปดา	 
# ๑	อาทิตย์	11 : มีน	22	33	
# ๒	จันทร์

* The Duang Chata
\label{duangchata}

The /duang chata/ \thai{ดวงชะตา}, or /horasat/ \thai{โหราศาสตร์} represents date
and time by the positions of the celestial bodies. When it represents a day, the
positions are at the time of midnight.

$0\degree$ (Aries) is the spring equinox, the segments 0-11 are the /rasi/, the
segments 1-27 are the /nakshatra/ or lunar mansions.

#+begin_latex
\begin{marginfigure}[\baselineskip]
\raggedright\footnotesize
Wat Chai Phra Kiat:\\
\href{https://encrypted.google.com/maps/place/Wat+Chai+Phrakiat/@18.7886216,98.9857345,20z/}{Google Maps}\\
\href{https://www.renown-travel.com/temples/wat-chai-phra-kiat.html}{renown-travel.com}
\end{marginfigure}
#+end_latex

On the Thai historical inscriptions, the planets are labelled by a
number.\autocite[p. 79]{eade1995calendrical} The stone inscription below is
found on the base of the Buddha image at Wat Chai Phra Kiat, Chiang Mai, and
records the date of casting the image.\footnotemark{} The photo was republished by
JC Eade in his paper.\autocite{eade1993mangrai}

#+begin_latex
\footnotetext{The image caption in the paper places the inscription at Wat
Chang Kham, which is probably an editorial mistake. Wat Chang Kham is in the Nan
province, and the paper only discusses Wat Chai Phra Kiat in Chiang Mai.}
#+end_latex

We can look at the inscription and find the date for which the formulas
reproduce the given positions.

\bigskip

#+begin_latex
\begin{extrafullwidth}%
\begin{minipage}[c]{0.6\linewidth}%
\centering
\resizebox{\linewidth}{!}{\DuangChata[Sun={8/25/29}, Moon={9/20/50}, fancy]}
\par
\end{minipage}%
\begin{minipage}[c]{0.4\linewidth}%
\centering
\includegraphics[width=0.9\linewidth]{wat-chai-phra-kiat-buddha-inscription.png}
\par
\end{minipage}%
\end{extrafullwidth}
#+end_latex

\bigskip

Here we only calculate the Sun \theSun{} (1, \thai{๑}) and the Moon \theMoon{}
(2, \thai{๒}), this already allows us to identify day 298 in the lunar year, and
gives us the date as *1566 January 3*.

#+begin_latex
\begin{marginfigure}[-1.5\baselineskip]
\raggedright\footnotesize
The code at sec. \ref{golang-mangrai} prints:

\begin{verbatim}
Day: 298
Date: 1566 Jan 3
Horakhun: 338865
Tithi: 2
True Sun: 8:25°29'
True Moon: 9:20°50'
\end{verbatim}

$9:19\degree 13\minute$ notation represents \textit{rasi}, \textit{angsa} (degrees), \textit{lipda} (minutes).

$r:a\degree l\minute = r*30 + a + l/60$,\\
thus $289\degree 13\minute$ is $9:19\degree 13\minute$.
\end{marginfigure}
#+end_latex

\clearpage

*** notes                                                          :noexport:

https://encrypted.google.com/search?hl=en&q=Wat+Chai+Phra+kiat

Wat Kham
https://www.renown-travel.com/temples/wat-phra-that-chang-kham.html
https://en.wikipedia.org/wiki/Wat_Chang_Kham
http://www.memoryofthailand.com/Wat-Phrathat-Chang-Kham-Worawihan.html
https://en.wikivoyage.org/wiki/Nan
http://www.orientalarchitecture.com/thailand/nan/wat-phra-that-chang-kham.php

normal year: Prokkatimat ปรกติมาส

ปกติมาส, rtgs: (pi) pakatimat,

อธิกวาร, rtgs: (pi) athikawan

อธิกมาส, rtgs: (pi) athikamat

Rasi is 0-11, Nakshatra is 1-27. Sun = \theSun, Moon = \theMoon.

0:1\degree 2\minute = Rasi:Angsa\degree Lipda\minute or Rasi:Degree\degree Minute\minute.

https://en.wikipedia.org/wiki/Nakshatra 
Nakshatra, Thai
https://th.wikipedia.org/wiki/%E0%B8%94%E0%B8%B2%E0%B8%A7%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%82%E0%B8%B1%E0%B8%95%E0%B8%A4%E0%B8%81%E0%B8%A9%E0%B9%8C
    
https://en.wikipedia.org/wiki/Lunar_mansion
https://en.wikipedia.org/wiki/Twenty-Eight_Mansions

https://en.wikipedia.org/wiki/Zodiac#Hindu_astrology_and_the_Zodiac

Zodiac, Thai
https://th.wikipedia.org/wiki/%E0%B8%88%E0%B8%B1%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%B2%E0%B8%A8%E0%B8%B5

http://www.thaiworldview.com/bouddha/animism4.htm

** Rasi

#+latex: \marginpar{\vspace*{-\baselineskip} Thai: rasi \thai{ราศี}}

The circle is divided into 12 segments called /rasi/, each marking 30 degrees.
Their numbering starts from 0, to express $x*30\degree$. See Table
\ref{tbl-rasi-names}.
   
#+begin_latex
\begin{table}[h]
\caption{\label{tbl-rasi-names} Names of the 12 Rasi.}

\begin{multicols}{2}
#+end_latex

|    | Western     | Sanskrit | Thai        |
|----+-------------+----------+-------------|
|  0 | Aries       | Meṣa     | \thai{เมษ}  |
|  1 | Taurus      | Vṛṣabha  | \thai{พฤษภ} |
|  2 | Gemini      | Mithuna  | \thai{เมถุน} |
|  3 | Cancer      | Karkaṭa  | \thai{กรกฎ} |
|  4 | Leo         | Siṃha    | \thai{สิงห์}  |
|  5 | Virgo       | Kanyā    | \thai{กันย์}  |

\columnbreak

|    | Western     | Sanskrit | Thai        |
|----+-------------+----------+-------------|
|  6 | Libra       | Tulā     | \thai{ตุลย์}  |
|  7 | Scorpio     | Vṛścika  | \thai{พิจิก}  |
|  8 | Sagittarius | Dhanus   | \thai{ธนู}   |
|  9 | Capricorn   | Makara   | \thai{มังกร} |
| 10 | Aquarius    | Kumbha   | \thai{กุมภ์}  |
| 11 | Pisces      | Mīna     | \thai{มีน}   |

#+begin_latex
\end{multicols}
\end{table}
#+end_latex

** Nakshatra, lunar mansions

#+latex: \marginpar{\vspace*{-\baselineskip} Thai: naksat \thai{นักษัตร}}

JC Eade in /Calendrical Systems/:

The Thai term for nakshatra is "raek", and the Burmese term is "nekkhat". The
reference is to the 27 segments into which the moon's orbit is
divided.\footnote{The Southeast Asian system makes no use of a 28th raek.} Each
segment is therefore $13\degree 20\minute$ in extent, and the inclination of the
Moon's orbit relative to the Sun's orbit is not taken into account, so that the
lunar mansions can be considered as lying in the same plane as the Sun's rasi.
In very general terms, and since the Moon's average motion is $13\degree$ a day,
the Moon can be considered to traverse one lunar mansion per day.\autocite[p. 31]{eade1995calendrical}
   
The names of the lunar month are derived from the name of the nakshatra that the
Moon will normally be occupying at Full Moon. But caution is required: since the
Moon's speed varies sharply, it may be that the mansion at Full Moon is one
(even two) short of, or past, where it "ought" to be.\autocite[p. 34]{eade1995calendrical}

#+begin_latex
\begin{table}[h]
\begin{extrafullwidth}
\caption{\label{tbl-nakshatra-names} Names of the 27 Nakshatra.}
\begin{multicols}{3}
\small
#+end_latex

|   | Sanskrit   | Thai           |
|---+------------+----------------|
| 1 | Ashvinī    | \thai{อัศวินี}    |
| 2 | Bharanī    | \thai{ภรณี}     |
| 3 | Kṛttikā    | \thai{กฤติกา}   |
| 4 | Rohinī     | \thai{โรหิณี}    |
| 5 | Mrigashīra | \thai{มฤคศีรษะ} |
| 6 | Ārdrā      | \thai{อาทรา}   |
| 7 | Punarvasu  | \thai{ปุนวสุ}    |
| 8 | Pushya     | \thai{ปุษยะ}    |
| 9 | Āshleshā   | \thai{อาศเลศา} |

\columnbreak

|    | Sanskrit        | Thai           |
|----+-----------------+----------------|
| 10 | Maghā           | \thai{มฆา}     |
| 11 | Pūrva Phalgunī  | \thai{บูรพผลคุณี} |
| 12 | Uttara Phalgunī | \thai{อุตรผลคุณี} |
| 13 | Hasta           | \thai{หัสตะ}    |
| 14 | Chitrā          | \thai{จิตรา}    |
| 15 | Svātī           | \thai{สวาตี}    |
| 16 | Vishākhā        | \thai{วิศาขา}   |
| 17 | Anurādhā        | \thai{อนุราธา}  |
| 18 | Jyeshtha        | \thai{เชษฐะ}   |

\columnbreak

|    | Sanskrit          | Thai            |
|----+-------------------+-----------------|
| 19 | Mūla              | \thai{มูละ}      |
| 20 | Pūrva Ashādhā     | \thai{บูรพาษาฒ}  |
| 21 | Uttara Ashādhā    | \thai{อุตราษาฒ}  |
| 22 | Shravana          | \thai{ศรวณะ}    |
| 23 | Dhanistha         | \thai{ศรวิษฐะ}   |
| 24 | Shatabhisha       | \thai{ศตภิษัช}    |
| 25 | Pūrva Bhādrapadā  | \thai{บูรพภัทรบท} |
| 26 | Uttara Bhādrapadā | \thai{อุตรภัทรบท} |
| 27 | Revatī            | \thai{เรวตี}     |

#+begin_latex
\end{multicols}
\end{extrafullwidth}
\end{table}
#+end_latex

\label{duangchata-end}

\clearpage

*** notes                                                          :noexport:

https://en.wikipedia.org/wiki/Nakshatra 

https://th.wikipedia.org/wiki/%E0%B8%94%E0%B8%B2%E0%B8%A7%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%82%E0%B8%B1%E0%B8%95%E0%B8%A4%E0%B8%81%E0%B8%A9%E0%B9%8C

* In Golang
\label{suriya-go-example}

Going through all this may be intriguing to calculate once, but mention
repeating it every year, then checking and proofing it, and one is reminded of a
phrase in Eade's /Calendrical Systems/: "Few would undertake cheerfully the
task."\autocite{eade1995calendrical}

Better tell the machine how to do it and let us get on with living. Let's
import [[https://github.com/splendidmoons/suriya-go][suriya-go]] and ask the machine in Golang.

** Year 1288
\label{golang-1288}

We will investigate 14 April 1288, and while doing that, also 15 June 1288,
which should turn out to be the date of Āsāḷha Pūjā.

#+latex: \inputminted{go}{./includes/print-1288.go}

\clearpage

Which prints:

: Year: 1288
: Adhikamāsa: false
: Adhikavāra: false
: ---
: Year, Day: 1288, 41
: True Sun: 0:19°58'
: True Moon: 5:11°27'
: Tithi: 12
: ---
: Year, Day: 1288, 103
: True Sun: 2:19°9'
: True Moon: 8:19°1'
: Tithi: 15

** Date of Casting of the Mangrai Buddha
\label{golang-mangrai}

#+latex: \inputminted{go}{./includes/print-wat-kiat.go}

\bigskip

Which prints:

#+begin_latex
\begin{verbatim}
Day: 298
Date: 1566 Jan 3
Horakhun: 338865
Tithi: 2
True Sun: 8:25°29'
True Moon: 9:20°50'
\end{verbatim}
#+end_latex

\clearpage

* Gregorian leap years

#+begin_quote
\logic{if} (/year/ is not exactly divisible by 4) \logic{then} (it is a common year)\\
\logic{else}\\
\logic{if} (/year/ is not exactly divisible by 100) \logic{then} (it is a leap year)\\
\logic{else}\\
\logic{if} (/year/ is not exactly divisible by 400) \logic{then} (it is a common year)\\
\logic{else} (it is a leap year)
\autocite{wp-leap-year}
#+end_quote

\backmatter

* Reading the Thai calendar layout                                 :noexport:

#+latex: \href{http://www.myhora.com/%E0%B8%9B%E0%B8%8F%E0%B8%B4%E0%B8%97%E0%B8%B4%E0%B8%99/%E0%B8%9B%E0%B8%8F%E0%B8%B4%E0%B8%97%E0%B8%B4%E0%B8%99-100%E0%B8%9B%E0%B8%B5-%E0%B8%9E.%E0%B8%A8.2558.aspx}{myhora.com - 2015}

#+latex: \href{http://horoscope.thaiorc.com/calendar/thaicalendar.php?y=2558}{horoscope.thaiorc.com - 2015}
  
#+begin_latex
\begin{fullwidth}
\centering
\includegraphics[width=\linewidth]{2015-myhora.png}
\end{fullwidth}
#+end_latex

* Adding the extra month, Pali method                              :noexport:
\label{pali-method}

# TODO: error in Aj H's sheet. 2002 is not adhikamāsa, he concatenates the cycles too early.

/The following is adapted from Ajahn Khemanando for recent
years./\autocite{khemanando-adhikamasa}

Table \ref{tbl-adhikamasa-pali} shows adding the adhikamāsa in the 19-year
cycle between 2001-2020.

#+attr_latex: :placement [h] :caption \caption{\label{tbl-adhikamasa-pali} Adding the adhikamāsa for 2001-2020 according to the Pali method.}\legend{\Delta m for years since last adhikamāsa. Months and moon are in Thai lunar months.}
|      |      | Nth | \Delta m | Season | Month | New      | Full      |
|------+------+-----+----------+--------+-------+----------+-----------|
| 2001 | 2544 |  19 |        2 | Cold   |     2 | \mN{} 12 | \mF{} 5   |
| 2002 | 2545 |   1 |          |        |       |          |           |
| 2003 | 2546 |   2 |          |        |       |          |           |
| 2004 | 2547 |   3 |        3 | Rainy  |    10 | \mN{} 8  | \mF{} 12  |
| 2005 | 2548 |   4 |          |        |       |          |           |
| 2006 | 2549 |   5 |          |        |       |          |           |
| 2007 | 2550 |   6 |        3 | Hot    |     7 | \mN{} 4  | \mF{} 8/8 |
| 2008 | 2551 |   7 |          |        |       |          |           |
| 2009 | 2552 |   8 |        2 | Cold   |     3 | \mN{} 12 | \mF{} 5   |
| 2010 | 2553 |   9 |          |        |       |          |           |
| 2011 | 2554 |  10 |          |        |       |          |           |
| 2012 | 2555 |  11 |        3 | Cold   |    12 | \mN{} 12 | \mF{} 5   |
| 2013 | 2556 |  12 |          |        |       |          |           |
| 2014 | 2557 |  13 |          |        |       |          |           |
| 2015 | 2558 |  14 |        3 | Rainy  |     8 | \mN{} 8  | \mF{} 12  |
| 2016 | 2559 |  15 |          |        |       |          |           |
| 2017 | 2560 |  16 |          |        |       |          |           |
| 2018 | 2561 |  17 |        3 | Hot    |     5 | \mN{} 4  | \mF{} 8/8 |
| 2019 | 2562 |  18 |          |        |       |          |           |
| 2020 | 2563 |  19 |        2 | Cold   |     2 | \mN{} 12 | \mF{} 5   |

- \Delta m: :: years since the last adhikamāsa 
- Month: :: the Thai lunar month into which the adhikamāsa is inserted
- Season: :: the season in which the adhikamāsa falls in that particular year
- New and Full: :: the first and last uposatha of the 5-month season in which
                   the adhikamāsa falls, numbered in Thai lunar months

If the adhikamāsa falls on the 2nd, 3rd, or 12th Thai lunar month,
there will be /two/ 8th months (8 and 8/8) the following year.

E.g. In 2001, the adhikamāsa comes as the 2nd lunar month in the Cold Season, so
the following year, 2002, has two 8th months (8 and 8/8). There will thus be
/ten/ uposathas in the Cold Season. The first being the New Moon of the 12th
Thai lunar month (of 2543, at the end of 2000), the last being the Full Moon
of the 5th Thai lunar month in 2001.

# Clear floats
\clearpage

* Websites and Apps                                                :noexport:

TODO

myhora.com

http://horoscope.thaiorc.com/calendar/thaicalendar.php

uposatha app

* Glossary                                                         :noexport:

Aka 

month: duean เดือน

month 8/8: เดือน ๘/๘

Waxing : khang khuen (ข้างขึ้น), the period from new moon to full moon, is always 15 days long.
Waning : khang raem (ข้างแรม), the period from full moon to new moon

* Colophon

[[http://orgmode.org/][Org-mode]] and \LaTeX. Sources at [[https://github.com/profound-labs/calculating-the-uposatha-moondays/][Github]].

Please send comments, corrections and further information to:

=Gambhiro Bhikkhu <gambhiro.bhikkhu.85@gmail.com>=

Last updated on {{{modification-time(%Y-%m-%d)}}}.

* Bibliography
\label{bibliography}

#+begin_latex
\printbibliography
#+end_latex

* Full page includes
  
Full page includes follow.

#+begin_latex
\fullpage{%
\label{dia-common-adhikamasa-adhikavara}%
\includegraphics[width=\paperwidth]{common-adhikamasa-adhikavara.png}%
}

\fullpage{%
\label{year-2014}%
\includegraphics[angle=90,width=\paperwidth]{2014-fs-year-planner-A4.pdf}%
}

\fullpage{%
\label{year-2015}%
\includegraphics[angle=90,width=\paperwidth]{2015-fs-year-planner-A4.pdf}%
}

\fullpage{%
\label{year-2016}%
\includegraphics[angle=90,width=\paperwidth]{2016-fs-year-planner-A4.pdf}%
}

#+end_latex
